apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow-deployment
  labels:
    app: hellow
spec:
  selector:
    matchLabels:
      app: hellow
  template:
    metadata:
      labels:
        app: hellow
    spec:
      containers:
      - name: hello-web
        image: hello-app:latest
# Use the localhost:32000 path to use image from registry service
# e.g.  image: localhost:32000/hello-app:v3
        ports:
        - containerPort: 8080
